<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Smart Office</title>
</head>

<body>
    @php
    $edate = date("d/m/Y", strtotime($expire_date));
    @endphp
    {{-- <p> <span style="color:blue;">TO:</span> {{ $from_email }} </p> --}}
    <p> <span style="color:blue;">Subject:</span> {{ $subject }} </p> 
    <li>This mail is generated by automated system, Do not reply to this mail.</li>
    <li>Click the following link to download the required document(s).</li> 
    <li>Use the provided "User ID" and "Password" to access the link.</li>
    <li>This file "{{ $file_name }}" link will expire on {{ $edate }}, kindly download the file prior to that date.</li>
    
    <br><br>
    Link : <a href="{{$link}}"> {{$link}}</a>
    <br><br>

    <strong><li style="list-style-type: none;">Login ID: {{ $to_email }}</li></strong>
    <strong><li style="list-style-type: none;">Password: {{ $random_password }}</li></strong>

</body>

</html>


